# Scanorama, Hie 2024
- id: doi:10.1038/s41596-024-00991-3
  buttons:
    - type: source
      link: https://github.com/brianhie/scanorama

# Singh 2024
- id: doi:10.1016/j.cels.2024.04.005

# Hong 2024
- id: doi:10.1007/978-1-0716-3989-4_19
  buttons:
    - type: source
      link: https://github.com/froelich/sf-relate

# AlphaFlow, Jing 2024
- id: doi:10.48550/arXiv.2402.04845
  buttons:
    - type: source
      link: https://github.com/bjing2016/alphaflow

# Jing 2023
- id: doi:10.48550/arXiv.2312.04323
  buttons:
    - type: source
      link: https://github.com/bjing2016/scalar-fields

# Sledzieski 2023
- id: doi:10.1101/2023.11.09.566187

# Sledzieski 2023
- id: doi:10.1093/bioinformatics/btad663
  buttons:
    - type: source
      link: https://github.com/samsledje/D-SCRIPT

# Pao-Huang 2023
- title: Scalable Multimer Structure Prediction using Diffusion Models
  authors:
    - Peter Pao-Huang
    - Bowen Jing
    - Bonnie Berger
  publisher: NeurIPS 2023 AI for Science Workshop
  date: 2021-10-28
  link: https://openreview.net/forum?id=SV6mT8iSFP

# SCA, DeMeo 2023
- id: doi:10.1186/s13059-023-02998-7
  buttons:
    - type: source
      link: https://github.com/bendemeo/shannonca

# sfkit, Mendelsohn 2023
- id: doi:10.1093/nar/gkad464

# mapquik, Ekim 2023
- id: doi:10.1101/gr.277679.123
  buttons:
    - type: source
      link: https://github.com/ekimb/mapquik

# Sadhuka 2023
- id: doi:10.1101/gr.277699.123
  buttons:
    - type: source
      link: https://github.com/shuvom-s/DSM

# Singh 2023
- id: doi:10.1073/pnas.2220778120
  buttons:
    - type: source
      link: https://github.com/samsledje/ConPLex_dev

# Froelicher 2023
- id: doi:10.1109/SP46215.2023.10179350

# AbMAP, Singh 2023
- id: doi:10.1101/2023.04.26.538476
  buttons:
    - type: source
      link: https://github.com/rs239/ablm

# EigenFold, Jing 2023
- id: doi:10.48550/arXiv.2304.02198
  buttons:
    - type: source
      link: https://github.com/bjing2016/EigenFold

# review, Berger 2023
- id: doi:10.1038/s41576-022-00551-z

# GrID-Net, Wu 2023
- id: doi:10.1101/2023.03.02.530529
  buttons:
    - type: source
      link: https://github.com/alexw16/gridnet

# Kinman 2023
- id: doi:10.1038/s41596-022-00763-x

# sequre, Smajlovic 2023
- id: doi:10.1186/s13059-022-02841-5
  buttons:
    - type: source
      link: https://github.com/0xTCG/sequre

# ConPLex, Sledzieski 2022
- id: doi:10.1101/2022.12.06.519374
  buttons:
    - type: source
      link: https://github.com/samsledje/ConPLex

# Cho 2022
- id: doi:10.1101/2022.11.30.518537
  buttons:
    - type: source
      link: https://github.com/hhcho/sfgwas

# Another CON-Plex paper, Sledzieski 2022
- id: doi:10.1101/2022.11.03.515086
  buttons:
    - type: source
      link: https://zenodo.org/records/7127229

# Sledzieski 2022
- id: doi:10.1101/2022.11.03.515084

# Sherman 2022
- id: doi:10.1038/s41587-022-01353-8
  buttons:
    - type: source
      link: https://github.com/maxwellsh/DIGDriver

# CryoDRGN2, Zhong 2022
- id: doi:10.1017/S1431927622005062

# Singh 2022
- id: doi:10.1101/2022.06.27.497786

# SafeGENIE, Chen 2022
- id: doi:10.1101/2022.05.20.492837

# Nyquist 2022
- id: doi:10.1073/pnas.2121720119
  buttons:
    - type: source
      link: https://github.com/ShalekLab/MIT_Milk_Study

# Shan 2022
- id: doi:10.1073/pnas.2122954119
  buttons:
    - type: source
      link: https://github.com/HeliXonProtein/binding-ddg-predictor

# TAD Map, Singh 2022
- id: doi:10.1101/2021.10.28.466333
  buttons:
    - type: source
      link: https://cb.csail.mit.edu/cb/tadmap/

# D-SCRIPT, Sledzieski 2022
- id: doi:10.1016/j.cels.2021.08.010
  buttons:
    - type: source
      link: https://dscript.csail.mit.edu/

# mdBG, Ekim 2021
- id: doi:10.1016/j.cels.2021.08.009
  buttons:
    - type: source
      link: https://github.com/ekimb/rust-mdbg

# seq, Shajii 2021
- id: doi:10.1038/s41587-021-00985-6
  buttons:
    - type: source
      link: https://seq-lang.org/

# Cryofold, Zhong 2021
- id: doi:10.48550/arXiv.2107.01331

# ShareNet, Wu 2021
- id: doi:10.1093/bioinformatics/btab269
  buttons:
    - type: source
      link: https://github.com/alexw16/sharenet

# ProSE, Bepler 2021
- id: doi:10.1016/j.cels.2021.05.017
  buttons:
    - type: source
      link: https://github.com/tbepler/prose.

# deSNE and densMAP, Narayan 2021
- id: doi:10.1038/s41587-020-00801-7
  buttons:
    - type: source
      link: https://cb.csail.mit.edu/cb/densvis/

# Schema, Singh 2021
- id: doi:10.1186/s13059-021-02313-2
  buttons:
    - type: source
      link: https://github.com/rs239/schema

# CryoDRGN, Zhong 2021
- id: doi:10.1038/s41592-020-01049-4
  buttons:
    - type: source
      link: https://www.github.com/zhonge/cryodrgn_empiar

# Hie 2021
- id: doi:10.1126/science.abd7331
  buttons:
    - type: source
      link: https://github.com/brianhie/viral-mutation
